services:
  - type: web
    name: big-question-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
